spring.application.name=rest-services-json-requst-response-body-db


#database properties

spring.datasource.url= jdbc:postgresql://localhost:5432/MIT
spring.datasource.username= postgres
spring.datasource.password= postgres
#spring.jpa.hibernate.ddl-auto=create

#spring.jpa.show-sql= true


server.port=8854
server.servlet.context-path=/api
